import { StyleSheet } from "react-native";

export const tenantStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#E7F4F8" },
  header: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0A556B",
  },
  back: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.15)",
    minWidth: 64,
  },
  backSpacer: { minWidth: 64 },
  backText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  title: { color: "#fff", fontWeight: "700", fontSize: 16, flex: 1, textAlign: "center" },
  scroll: { padding: 16, paddingBottom: 48 },
  banner: {
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#F8FCFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  bannerText: { color: "#577783", fontSize: 14, lineHeight: 20 },
  search: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#0D2630",
  },
  card: {
    marginBottom: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#F4FAFC",
    padding: 16,
  },
  cardTitle: { fontSize: 16, fontWeight: "700", color: "#0D2630" },
  cardSub: { marginTop: 4, fontSize: 13, color: "#577783", lineHeight: 18 },
  badge: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#E7F4F8",
  },
  badgeText: { fontSize: 11, fontWeight: "600", color: "#0A556B" },
  badgeInactive: { backgroundColor: "#F5E6E6" },
  badgeInactiveText: { color: "#8B1E1E" },
  badgePending: { backgroundColor: "#FFF4E5" },
  badgePendingText: { color: "#9A6700" },
  rowMeta: { marginTop: 6, fontSize: 12, color: "#8AA3AD" },
  center: { paddingVertical: 40, alignItems: "center" },
  errorBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F5C2C2",
    backgroundColor: "#FFF5F5",
    padding: 16,
  },
  errorText: { color: "#8B1E1E", fontSize: 14, lineHeight: 20 },
  retry: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#0A556B",
  },
  retryText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  sectionTitle: {
    marginTop: 8,
    marginBottom: 8,
    fontSize: 13,
    fontWeight: "700",
    color: "#577783",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  statTile: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#F4FAFC",
    padding: 12,
    alignItems: "center",
  },
  statValue: { fontSize: 22, fontWeight: "700", color: "#0D2630" },
  statLabel: { marginTop: 2, fontSize: 11, color: "#8AA3AD" },
  linkCard: {
    marginBottom: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#0A556B",
    backgroundColor: "#0A556B",
    padding: 16,
  },
  linkTitle: { color: "#fff", fontWeight: "700", fontSize: 15 },
  linkSub: { marginTop: 4, color: "#C8E6EF", fontSize: 13 },
  meta: { marginTop: 8, fontSize: 11, color: "#8AA3AD", lineHeight: 16 },
});
