import { StyleSheet } from "react-native";

export const tenantStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#E7F4F8" },
  header: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0A556B",
  },
  back: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.15)",
    minWidth: 64,
  },
  backSpacer: { minWidth: 64 },
  backText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  title: { color: "#fff", fontWeight: "700", fontSize: 17, flex: 1, textAlign: "center" },
  scroll: { padding: 16, paddingBottom: 48 },
  banner: {
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#F8FCFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  bannerText: { color: "#577783", fontSize: 14, lineHeight: 20 },
  search: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#0D2630",
  },
  card: {
    marginBottom: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#F4FAFC",
    padding: 16,
  },
  cardTitle: { fontSize: 17, fontWeight: "700", color: "#0D2630" },
  cardSub: { marginTop: 4, fontSize: 14, color: "#577783", lineHeight: 20 },
  badge: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#E7F4F8",
  },
  badgeText: { fontSize: 11, fontWeight: "600", color: "#0A556B" },
  badgeInactive: { backgroundColor: "#F5E6E6" },
  badgeInactiveText: { color: "#8B1E1E" },
  badgePending: { backgroundColor: "#FFF4E5" },
  badgePendingText: { color: "#9A6700" },
  rowMeta: { marginTop: 6, fontSize: 12, color: "#8AA3AD" },
  center: { paddingVertical: 40, alignItems: "center" },
  errorBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F5C2C2",
    backgroundColor: "#FFF5F5",
    padding: 16,
  },
  errorText: { color: "#8B1E1E", fontSize: 14, lineHeight: 20 },
  retry: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#0A556B",
  },
  retryText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  sectionTitle: {
    marginTop: 8,
    marginBottom: 8,
    fontSize: 13,
    fontWeight: "700",
    color: "#577783",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  statTile: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#F4FAFC",
    padding: 12,
    alignItems: "center",
  },
  statTilePressable: { minHeight: 72 },
  statTileDisabled: {
    opacity: 0.72,
    borderColor: "#E2EEF2",
    backgroundColor: "#F8FAFB",
  },
  statValue: { fontSize: 22, fontWeight: "700", color: "#0D2630" },
  statValueDisabled: { color: "#8AA3AD" },
  statLabel: { marginTop: 2, fontSize: 11, color: "#8AA3AD" },
  statChevron: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: "700",
    color: "#0A556B",
  },
  statSoon: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: "600",
    color: "#8AA3AD",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  entitlementReadOnlyBanner: {
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#E7F4F8",
    borderWidth: 1,
    borderColor: "#C8E6EF",
  },
  entitlementReadOnlyText: {
    fontSize: 12,
    color: "#577783",
    lineHeight: 17,
  },
  heroCard: {
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#0A556B",
    backgroundColor: "#0A556B",
    padding: 20,
  },
  heroTitle: { color: "#fff", fontWeight: "800", fontSize: 18 },
  heroSub: { marginTop: 6, color: "#C8E6EF", fontSize: 14, lineHeight: 20 },
  linkCard: {
    marginBottom: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#0A556B",
    backgroundColor: "#0A556B",
    padding: 16,
  },
  linkTitle: { color: "#fff", fontWeight: "700", fontSize: 15 },
  linkSub: { marginTop: 4, color: "#C8E6EF", fontSize: 13 },
  meta: { marginTop: 8, fontSize: 13, color: "#8AA3AD", lineHeight: 18 },
  deckHero: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 10,
    borderRadius: 18,
    backgroundColor: "#0A556B",
    padding: 18,
  },
  deckHeroTitleRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  deckHeroLogo: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  deckHeroLogoText: { color: "#0A556B", fontWeight: "800", fontSize: 22 },
  deckHeroTitleBlock: { flex: 1, minWidth: 0 },
  deckHeroTitleLine: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  deckHeroTitle: { color: "#fff", fontWeight: "800", fontSize: 20 },
  deckHeroActiveBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#D4F5E0",
  },
  deckHeroActiveText: { fontSize: 12, fontWeight: "700", color: "#1B6B3A" },
  deckHeroInactiveBadge: { backgroundColor: "#F5E6E6" },
  deckHeroInactiveText: { color: "#8B1E1E" },
  deckHeroContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  deckHeroContact: { fontSize: 14, color: "#C8E6EF", lineHeight: 19, flexShrink: 1 },
  deckHeroPlanRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  deckHeroPlan: { fontSize: 15, fontWeight: "600", color: "#fff", flexShrink: 1 },
  deckHeroPlanRowInline: { marginTop: 4 },
  deckHeroBarRow: { marginTop: 12 },
  deckHeroBarLabel: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  deckHeroBarLabelText: { fontSize: 13, color: "#C8E6EF", fontWeight: "500" },
  deckHeroBarPct: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0A556B",
    backgroundColor: "#C8E6EF",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    overflow: "hidden",
  },
  deckHeroBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.2)",
    overflow: "hidden",
  },
  deckHeroBarFill: { height: 8, borderRadius: 999, backgroundColor: "#5BC4E8" },
  deckHeroBarFillAlt: { backgroundColor: "#7EB6FF" },
  segmentRow: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  segmentBtnActive: { backgroundColor: "#0A556B" },
  segmentBtnDisabled: { opacity: 0.55 },
  segmentLabel: { fontSize: 13, fontWeight: "700", color: "#577783", textAlign: "center" },
  segmentLabelActive: { color: "#fff" },
  segmentLabelDisabled: { color: "#8AA3AD" },
  segmentCount: { fontSize: 12, fontWeight: "700", color: "#8AA3AD" },
  segmentCountActive: { color: "#C8E6EF" },
  segmentSoon: {
    fontSize: 10,
    fontWeight: "800",
    color: "#8AA3AD",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  factSection: { marginBottom: 14 },
  factSectionCaption: {
    marginBottom: 8,
    marginLeft: 2,
    fontSize: 12,
    fontWeight: "800",
    color: "#8AA3AD",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  factSheet: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  factRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E2EEF2",
    gap: 12,
    minHeight: 52,
  },
  factRowFirst: { borderTopWidth: 0 },
  factRowIcon: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  factRowBody: { flex: 1, minWidth: 0 },
  factRowLabel: { fontSize: 13, color: "#8AA3AD", fontWeight: "600", marginBottom: 2 },
  factRowValue: { fontSize: 16, color: "#0D2630", fontWeight: "600", lineHeight: 22 },
  factRowValueGood: { color: "#1B6B3A" },
  factRowTrailing: { marginLeft: 4 },
  factFootnote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E2EEF2",
  },
  factFootnoteText: {
    flex: 1,
    fontSize: 13,
    color: "#8AA3AD",
    lineHeight: 18,
  },
  billingDrawer: {
    marginTop: 2,
    marginBottom: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  billingDrawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  billingDrawerTextBlock: { flex: 1, minWidth: 0 },
  billingDrawerTitle: { fontSize: 16, fontWeight: "700", color: "#0D2630" },
  billingDrawerSub: { marginTop: 3, fontSize: 13, color: "#8AA3AD" },
  billingDrawerChevron: { fontSize: 16, color: "#8AA3AD", fontWeight: "700" },
  billingDrawerBody: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E2EEF2",
  },
  billingDrawerBodyText: { marginTop: 10, fontSize: 14, color: "#577783", lineHeight: 20 },
  paneListCard: {
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  paneListBody: { flex: 1 },
  paneListBadge: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#0A556B",
  },
  paneListBadgeText: { fontSize: 12, fontWeight: "700", color: "#fff" },
  paneListChevron: { marginLeft: 6, fontSize: 20, fontWeight: "700", color: "#8AA3AD" },
  paneEmpty: {
    marginTop: 24,
    padding: 28,
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
  },
  paneEmptyTitle: { fontSize: 17, fontWeight: "700", color: "#577783" },
  paneEmptySub: { marginTop: 10, fontSize: 14, color: "#8AA3AD", textAlign: "center", lineHeight: 20 },
  paneToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  paneAddBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#0A556B",
  },
  paneAddText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  contentFlex: { flex: 1 },
  deckHeroCompact: { padding: 14, marginBottom: 8 },
  deckHeroLogoCompact: { width: 42, height: 42, borderRadius: 10 },
  deckHeroLogoTextCompact: { fontSize: 18 },
  deckHeroTitleCompact: { fontSize: 17 },
  deckHeroPlanCompact: { fontSize: 13, marginTop: 0 },
  paneSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  paneSearch: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C8E6EF",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
  },
  paneSearchInput: {
    flex: 1,
    fontSize: 15,
    color: "#0D2630",
    padding: 0,
  },
  paneCountCaption: {
    marginBottom: 10,
    fontSize: 12,
    fontWeight: "800",
    color: "#8AA3AD",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  paneIconTile: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#E7F4F8",
    borderWidth: 1,
    borderColor: "#C8E6EF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  paneAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#0A556B",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  paneAvatarMuted: { backgroundColor: "#CBDDE4" },
  paneAvatarText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  paneAvatarTextMuted: { color: "#577783" },
  paneRowMetaLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  paneSeatPill: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#E7F4F8",
    borderWidth: 1,
    borderColor: "#C8E6EF",
  },
  paneSeatPillFilled: {
    backgroundColor: "#0A556B",
    borderColor: "#0A556B",
  },
  paneSeatPillText: { fontSize: 11, fontWeight: "800", color: "#577783" },
  paneSeatPillTextFilled: { color: "#fff" },
  paneStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1B6B3A",
    marginRight: 2,
  },
  paneStatusDotMuted: { backgroundColor: "#8AA3AD" },
  tasksSoonCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
    padding: 22,
    alignItems: "center",
  },
  tasksSoonPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#E7F4F8",
    marginBottom: 16,
  },
  tasksSoonPillText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#0A556B",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  tasksSoonIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#E7F4F8",
    borderWidth: 1,
    borderColor: "#C8E6EF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  tasksSoonTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0D2630",
    textAlign: "center",
    marginBottom: 8,
  },
  tasksSoonBody: {
    fontSize: 14,
    color: "#577783",
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 16,
  },
  tasksSoonSheet: {
    alignSelf: "stretch",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2EEF2",
    backgroundColor: "#F8FCFF",
    overflow: "hidden",
    marginBottom: 14,
  },
  detailHero: {
    marginBottom: 14,
    borderRadius: 16,
    backgroundColor: "#0A556B",
    padding: 18,
  },
  detailHeroRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  detailHeroTitle: { color: "#fff", fontWeight: "800", fontSize: 20, flexShrink: 1 },
  detailHeroSub: { marginTop: 6, color: "#C8E6EF", fontSize: 14, lineHeight: 20 },
  destCard: {
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5E8EF",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 56,
  },
  destCardDisabled: { opacity: 0.55 },
  destCardBody: { flex: 1, minWidth: 0 },
  destCardLabel: { fontSize: 13, color: "#8AA3AD", fontWeight: "600" },
  destCardValue: { marginTop: 2, fontSize: 16, color: "#0D2630", fontWeight: "700" },
  destCardValueMuted: { color: "#8AA3AD" },
});
